### ISSUE TITLE
Need Some help but it's not a bug.

### ISSUE THREAD

**Issue by panpaterakis1** [Kurento/kurento-room#3]
Hello,

We have developed an application based on kurento room. In version 6.1 everything worked like a charm. Since the upgrade to version 6.2 of kurento media server and kurento room we have a problem with 403 error on websocket handsake . I believe it is a cross origin issue.  I'm trying to understand where should I allowOrigin in kurento room application. I have created a filter and I have "hacked" JsonRpcConfigurer of kurento-java-6.2 project to set allowOrigin . Neither of this worked. Any ideas on how to invoke kurento-room-demo with a custom remote client?

**Comment by jcaden** [comment]
Please, ask questions in the list, this is only for bugs.
